### PR TITLE
179 more control for recr dist in forecast

### LINKED ISSUE #68: add option for forecast to use averaged M or other biology parms
Trying a new prototype template here.  This section will continually be edited as development progress.
- [ ] Issue description
For various MGparms, notably M and recruitment distribution, there is a need to be able to calculate the average over some range of years during which the factor is time-varying, and to assign that average to each year of the forecast.

- [ ] summary of major aspects of code revision

- fcast_loop_control(5) is unused and will be re-purposed to invoke the needed inputs
-  add new list based input of MG_type, start year, end year
-    terminate with MG_type = -9999
-    for MG_type, use this scheme:  1=natural_mortality  (M), 2=growth, 3=wtlen, 4=recr_dist&femfrac, 5=migration, 6=ageerror, 7=catchmult, 8=hermaphroditism, 9=maturity&fecundity

- [ ] example input change, with zip
This new approach has input with 4 values that looks like this.
```
1 #_Fcast_MGparm_averaging: 0 = not, 1 = do
#_read list of MG_type, method (1, 2), start year, end year
#_Terminate with -9999 for MG_type
#_MG_type: 1=M, 2=growth, 3=wtlen, 4=recr_dist&femfrac, 5=migration, 6=ageerror, 7=catchmult, 8=hermaphroditism
#_Method = 0 (default) means continue time_vary parms; 1 means to use average of derived biology; 2 (future) means average parameter then apply as if time-vary
#_MG_type method st_year end_year 
1 1 2002 2003 # (M) NatMort 
4 1 2016 2018 # RecrDist 
-9999 -1 -1 -1

```
- [ ] example output change
- [ ] draft text for manual

----------------------------------------------------------------
History and commentary below
Imported from redmine, Issue [#75321](https://vlab.ncep.noaa.gov/redmine/issues/75321)
 Opened by @RickMethot on 2020-02-24
Status when imported: New
 
While working with Steve Barbeaux, we found a need to manually create a block for forecast years so that a M value calculated for benchmark years could be hardwired in as the forecast M.

The current forecast input does not allow for specifying biology:
#_Fcast_years:  beg_selex, end_selex, beg_relF, end_relF, beg_mean recruits, end_recruits  (enter actual year, or values of 0 or -integer to be rel. endyr)
 2018 2018 2014 2018 1977 2019

### PR DESCRIPTION
**Pull request by nschindler-noaa**
## Concisely (20 words or less) describe the issue
Adds capability to average Maturity and Growth parameters over a range of years for use in forecast.

## Please Link issue(s)
resolves #68 

## Has any new code been documented?

If not, please add documentation before submitting the Pull Request.
- [ ] I have documented any new code added (or no new code was added)

## is there an input change for users to Stock Synthesis? 

- [x] Yes, there was an input change

If so, please provide an example of the new inputs needed.
In issue #68

## Check which is true. This PR requires:

- [ ] no further changes to r4ss
- [ ] no further changes to the manual
- [ ] no further changes to SSI (the SS3 GUI)
- [ ] no further changes to the stock synthesis change log (new features, bug reports)

## If changes are needed in the change log, please fill in the table here:

| Action                | Topics                                     | Type  |
| --------------------- | ----------------------------------------- | --------------------------------------- |
| [fix, new, or revise] | [e.g., biology. Use issue label options.] | [input, output, and/or calc, or ALL] |

### CODE REVIEW

**Comment by iantaylor-NOAA** [comment]
Thanks for putting this together @nschindler-noaa.
Could you attach a data file with the example input to this issue or just paste an the new table into these comments?

**Comment by Rick-Methot-NOAA** [comment]
I am planning to take an example that has time-vary biology and use it to test out the feature today or tomorrow

**Comment by nschindler-noaa** [comment]
I modified simple to have a couple things. Not sure if it makes sense. 
[simple-MGave.zip](https://github.com/nmfs-stock-synthesis/stock-synthesis/files/11035029/simple-MGave.zip)

**Comment by Rick-Methot-NOAA** [comment]
Hi Neal.  Great start on this.  I created the attached set of files for a testbed and tried it out for natural mortality.
From the result I get for M, it seems that the averaging process is OK, but the result is only being put into the first year of the forecast, not all years (thru YrMax).

Also, it would be helpful to put a line in forecast.ss_new with the list of MGtypes and their code.
[fcast_bio_test.zip](https://github.com/nmfs-stock-synthesis/stock-synthesis/files/11035270/fcast_bio_test.zip)

**Comment by nschindler-noaa** [comment]
Okay. I'll make the change to write_new and look at what I can do on the rest.

**Comment by Rick-Methot-NOAA** [comment]
my bad.  I created an example for time-varying natural mortality (M), but that is not implemented yet in your code.

**Comment by nschindler-noaa** [comment]
Maturity averaging is not yet implemented. I tried to use the same years for recrdist and migrrate with no differences between the runs (I am comparing to a model with no forecast averaging).

**Comment by Rick-Methot-NOAA** [comment]
Here is an improved testbed.  Right now it is set to do averaging for recrdist.  Fails because of interaction with another approach to extending recrdist into the forecast, for which we will need some added collision avoidance and warnings.
[fcast_bio_test.zip](https://github.com/nmfs-stock-synthesis/stock-synthesis/files/11045052/fcast_bio_test.zip)

**Comment by nschindler-noaa** [comment]
@Rick-Methot-NOAA , as you expected, commenting out line 1765 in popdyn does not make a difference.

**Comment by Rick-Methot-NOAA** [comment]
now your turn to review my work.  Here is updated example.  See the last warning in list 
[fcast_bio_test.zip](https://github.com/nmfs-stock-synthesis/stock-synthesis/files/11095485/fcast_bio_test.zip)

**Comment by e-gugliotti-NOAA** [comment]
@Rick-Methot-NOAA I just tried running the artifact ss exe with your zip on my personal mac laptop and got the error 
`reading from starter.ss
Error trying to open data input file GOAPCod2019_14.dat`.
The exe worked for other models though. I'm not sure if @nschindler-noaa will also have this problem.

**Comment by Rick-Methot-NOAA** [comment]
sorry about that.  You'll need to modify the starter file to refer to data.ss and control.ss as the input file names

**Comment by e-gugliotti-NOAA** [comment]
@Rick-Methot-NOAA oh okay, yes I started to look into where those file names were specified but then had to head to OT.

**Comment by Rick-Methot-NOAA** [comment]
@nschindler-noaa 
Neal, can you work on averaging of M (mortality) next?  Can use the benchmark averaging code as prototype

**Comment by nschindler-noaa** [comment]
I tried to use the natM averaging code, but must have made a mistake. Get this error after 2 iterations: 
Error: Invalid index 43 used for array range [1974, 2069] in "dvar_vector& dvar4_array::operator() (int i, int j, int k)".
hslice index out of bounds

**Comment by Rick-Methot-NOAA** [comment]
Neal.  I got the natmort indexing fixed but now see that we need a more bulletproof way for the model to know whether to do average of time_varying values from the historical years, or to continue doing time-varying into the forecast.  In my next commit I will try an alternative.

**Comment by Rick-Methot-NOAA** [comment]
This new approach has input with 4 values that looks like this.  Next step will be using the method value to decide when to allow averaging to override time_vary parameters, with appropriate warnings.
`1 #_Fcast_MGparm_averaging: 0 = not, 1 = do
#_read list of MG_type, method (1, 2), start year, end year
#_Terminate with -9999 for MG_type
#_MG_type: 1=M, 2=growth, 3=wtlen, 4=recr_dist&femfrac, 5=migration, 6=ageerror, 7=catchmult, 8=hermaphroditism
#_Method = 0 (default) means continue time_vary parms; 1 means to use average of derived biology; 2 (future) means average parameter then apply as if time-vary
# MG_type method st_year end_year 
1 1 1 2002 2003 # (M) NatMort 
4 4 1 2016 2018 # RecrDist 
-9999 -1 -1 -1`

**Comment by Rick-Methot-NOAA** [comment]
Now code like this can override time_vary:
`      if (Fcast_MGparm_ave(1, 1) == 1)
      {
        //  array has been filled with averages already
      }
      else if (timevary_MG(y, 1) > 0 || N_pred > 0)
      {
        get_natmort();
      }
`

**Comment by Rick-Methot-NOAA** [comment]
@iantaylor-NOAA  Could you take a look at this new approach?  No rush.
[fcast_bio_test.zip](https://github.com/nmfs-stock-synthesis/stock-synthesis/files/11226639/fcast_bio_test.zip)

**Comment by iantaylor-NOAA** [comment]
@Rick-Methot-NOAA and @nschindler-noaa,
Nice work getting this new feature added. The new input format in forecast file makes sense. 
Testing it helped me discover a bug in how r4ss was parsing the M-at-age table as noted here: https://github.com/r4ss/r4ss/issues/789.

I confirmed that the M-at-age for 2019 and beyond is equal to the average of the M-at-age for the years 2002-2003 as specified in the forecast file. However, I'm not seeing that match in the recruitment allocation. I changed the forecast file to use
```
# MG_type method st_year end_year 
 1 1 2002 2003 # (M) NatMort 
 4 1 2012 2012 # RecrDist
```
since 2012 was the most extreme year among the recruitment allocations, but it appears that 2019 and beyond are much more similar to (but not exactly matching) 2018 rather than 2012 as shown in the r4ss figure and calculations below.
```
> # plot time series of fraction of recruits by area
> SSplotTimeseries(model, subplot = 13)

> # get recruits by area in 2012
> model$timeseries$Recruit_0[model$timeseries$Yr == 2012]
[1]  31703800 139019000
> # fraction of recruits in area 1 in 2012
> x = model$timeseries$Recruit_0[model$timeseries$Yr == 2012]
> x[1]/sum(x)
[1] 0.1857034
> # fraction of recruits in area 1 in 2018
> x = model$timeseries$Recruit_0[model$timeseries$Yr == 2018]
> x[1]/sum(x)
[1] 0.04475221
> # fraction of recruits in area 1 in 2019
> x = model$timeseries$Recruit_0[model$timeseries$Yr == 2019]
> x[1]/sum(x)
[1] 0.04639038
```

image

**Comment by Rick-Methot-NOAA** [comment]
I think the next feature aspect of this to develop is the averaging of the parameter values approach.  @nschindler-noaa -  let's talk that over tomorrow or next week.

**Comment by Rick-Methot-NOAA** [comment]
@nschindler-noaa @e-gugliotti-NOAA 
I think we should wrap up this issue with its existing capability.  Let's catch up on the degree to which it has been documented and then merge it it.

**Comment by Rick-Methot-NOAA** [comment]
work on the manual is still on my to-do list

**Comment by Rick-Methot-NOAA** [comment]
@nschindler-noaa 
Can you add one more bell&whistle to MGparm_averaging?

After the model reads the Fast_yr values, it compares them to styr and endyr to make adjustments.  This allows user to select -999 to change to styr, for example.  Can you replicate that capability for the Fcast_MGparm_ave values read a short ways below?
I just pushed a version with placeholder

**Review by Rick-Methot-NOAA — APPROVED** [review]
Looks good Neal

**Pull request merged**
