### PR TITLE
clean up and add comments for mat_fec calcs

### LINKED ISSUE #348: skip maturity- & fecundity-at-length calculations when values at age are input directly?
@latreesedenson-NOAA and @Matthew-Smith-NOAA reported an r4ss plotting issue https://github.com/r4ss/r4ss/issues/709 with their red snapper model which I tracked down as related to "Inf" values in the BIOLOGY table.

I replicated the issue in the attached modification of "Simple".

When maturity option 4=read age-fecundity is combined with placeholder 999 values for the maturity and fecundity parameters, fecundity-at-length is calculated as `999 * weight ^ 999` though these values have are not used in the model. 

I can make a fix to r4ss to skip the plots of length-based maturity and fecundity when maturity option 4 is used, but could we also report "NA" values for the "Mat_len", "Spawn", and "Fecundity" columns in BIOLOGY for models that use age-based maturity options or empirical weight-at-age? NA could be reported even if the fecundity is still being calculated, but I supposed skipping the calculation could also be nice (though presumably not very time-intensive if it only happens once).

An additional option would be to also skip the input of the parameters lines, saving users from adding placeholder values, but I assume that would take a lot more work.

[Simple_maturity4.zip](https://github.com/nmfs-stock-synthesis/stock-synthesis/files/9095691/Simple_maturity4.zip)

### PR DESCRIPTION
**Pull request by Rick-Methot-NOAA**
## What issue(s) does this PR address? 
resolves #348 

## Describe the issue, if not included in the PR
some aspects of maturity and fecundity were being calculated even in not used; calculated values could be nonsensical if user provided placeholder rather than realistic parameter values.  Solution:  replace output  in these situations with a constant vector of 0.5.  Augment comments in code to describe the relevant situations.
## What tests have been done? Upload any model input files created for testing in a zip file, if possible.
minimal
## What tests/review still need to be done? Who can do it, and by when is it needed (ideally)?
try it out with the setup identified in issue #348 
## is there an input change for users to Stock Synthesis? 
no
If so, please provide an example of the new inputs needed.

```
[New example stock synthesis input goes here]

```

## Check which is true. This PR requires:

- [ ] no further changes to r4ss
- [x] no further changes to the manual
- [x] no further changes to SSI (the SS3 GUI)
- [x] no further changes to the stock synthesis change log (new features, bug reports)

## Describe any changes in r4ss/SS3 manual/SSI that are needed (if not checked):
r4ss needs to adjust headers for the biology_report (no. 42)

## If changes are needed in the change log, please fill in the table here:

Version | Date       | Description               | Issue        | Input change | Action                | Topic                                     | Type  |
| ----- | ---------- | ---------------------- | ------------ | ------------ | --------------------- | ----------------------------------------- | --------------------------------------- |
3.30.20 | [Add date] | [add concise description] | #[add issue] | [yes or no]  | [fix, new, or revise] | [e.g., biology. Use issue label options.] | [input, output, and/or calc, or ALL] |

### CODE REVIEW

**Comment by Rick-Methot-NOAA** [comment]
@iantaylor-NOAA 
encounter r4ss error with test model: vermillion_snapper_F4

**Comment by k-doering-NOAA** [comment]
Thanks @iantaylor-NOAA for starting the re-run! Looks like it passed, so there is no issue with r4ss.

@iantaylor-NOAA , if you have the time, maybe you can review Rick's changes (or maybe you already have?) and "approve" the pull request if it is ready to merge in?

**Review by iantaylor-NOAA — APPROVED** [review]
Looks good. In addition to the automated tests, I ran the `r4ss::SS_plots()` function on models that had fecundity method 1 and 4 to confirm that things don't just run but look OK, which they do. I still need to turn off the length-based maturity and fecundity plots for the models that don't use those values, but for now the constant 0.5 value will make it clear that this isn't connected to the parameter lines.

I appreciate the extra message in the ss_new file about parameter lines needed.

**Comment by iantaylor-NOAA** [comment]
Since I requested no changed, I went ahead and merged and deleted the branch. Does that make sense or is it better to leave it to @Rick-Methot-NOAA to merge after the review is complete?

**Comment by iantaylor-NOAA** [comment]
Sounds good. I got carried away clicking through things after completing the review.

**Pull request merged**
