### PR TITLE
Add docker target to build file.

### PR DESCRIPTION
**Pull request by johnoel**
Add docker to build file.

### CODE REVIEW

**Comment by e-gugliotti-NOAA** [comment]
@johnoel, the commit I added was just a change to trigger the workflows to build ss3 with the changes to the makefile, will drop the commit after the check has passed.

**Comment by johnoel** [comment]
should be

pr_body  <- strsplit(info$body, split = "\n" )[[1]]

**Comment by e-gugliotti-NOAA** [comment]
It's just that there was nothing in the body of the PR to pull from with info$body. I put something in the body and it started working.

**Comment by e-gugliotti-NOAA** [comment]
I'm still not getting an opt version from this sadly. The linux workflow in github actions uses [this .sh file](https://github.com/nmfs-stock-synthesis/stock-synthesis/blob/main/Make_SS_330_new.sh) to create the executable. I don't know if there is a clue in that file that could help get the GNUMakefile to work. Maybe something similar to the lines 119-125 need to be added to the GNUMakefile?

**Comment by johnoel** [comment]
My bad, the target used the wrong filename.  To make it easier

```
make docker
```

will build both the optimized and safe version of ss.

Or, you can build separately.

Make the safe ss version

```
make docker_ss
```

Make the optimized ss version

```
make docker_ss_opt
```

**Comment by johnoel** [comment]
Okay, added docker command to Make_SS_330_new.sh.  To build with docker use the command below

```
stock-synthesis % ./Make_SS_330_new.sh --admb docker -w
```

ADMB_HOME is where docker is...

Notice the **-w** option.  The script will now build just once with the compiler warnings.  The second unneeded call to compile source code was removed.

**Comment by e-gugliotti-NOAA** [comment]
Okay so this IS running on codespaces which is amazing, but I'm having trouble getting it to run github actions, see test action [here](https://github.com/nmfs-stock-synthesis/stock-synthesis/actions/runs/6616322605/job/17970342961).  @johnoel  do you have any ideas or changes that I need to make to get it running?

**Comment by e-gugliotti-NOAA** [comment]
The main error is this:
/usr/local/bin/admb: line 361: admb.log: Permission denied
Error: could not parse "ss.tpl".

cat: admb.log: No such file or directory
make: *** [GNUmakefile:26: docker_ss] Error 1
Error: Process completed with exit code 2.

**Comment by johnoel** [comment]
Try again, just pushed a new docker image.

**Comment by e-gugliotti-NOAA** [comment]
Sadly, this is the error message that I am getting now:
Status: Downloaded newer image for johnoel/admb:linux
*** Parse: ss.tpl
tpl2cpp ss || tpl2rem ss

Error trying to open file xxhtop.tmp
Error trying to open file xxglobal.tmp
/usr/local/bin/admb: line 361:    27 Segmentation fault      (core dumped) tpl2cpp ss
Error trying to open file xxhtop.tmp
Error trying to open file xxglobal.tmp
/usr/local/bin/admb: line 361:    28 Segmentation fault      (core dumped) tpl2rem ss
Error: could not parse "ss.tpl".

cat: admb.log: No such file or directory
make: *** [GNUmakefile:26: docker_ss] Error 1
Error: Process completed with exit code 2.

**Comment by johnoel** [comment]
Strange, the mounted directory is read-only.  I will investigate a bit more...

**Comment by e-gugliotti-NOAA** [comment]
Okay, thanks for helping me with this. FYI, I will also eventually be trying to add the admb docker image to the workflow for linux and macOS, so will I likely have some more questions on that after we get this worked out.

**Comment by Rick-Methot-NOAA** [comment]
Thanks to both of you for working on this.  I can't help but will certainly appreciate  the result when you are done.

**Comment by e-gugliotti-NOAA** [comment]
I added "chmod -R 777 ." to the run line and the action is now successful - see [here](https://github.com/nmfs-stock-synthesis/stock-synthesis/actions/runs/6631130928/job/18013978980)

**Comment by e-gugliotti-NOAA** [comment]
Will try windows and macOS next

**Comment by e-gugliotti-NOAA** [comment]
Okay so I got it working on windows (so it seems) but now I'm running into issues with running the image on macos. The workflow that I am running is [here](https://github.com/nmfs-stock-synthesis/stock-synthesis/blob/admb-docker-images/.github/workflows/build-ss3.yml) and the failed action is [here](https://github.com/nmfs-stock-synthesis/stock-synthesis/actions/runs/6631930390/job/18016536377). The macos workflow to build ss3 uses the .Make_SS_330_new file.

**Comment by johnoel** [comment]
Shoots, I lost my changes...

**Comment by e-gugliotti-NOAA** [comment]
@johnoel have you had any more time to investigate this?

**Comment by johnoel** [comment]
Okay, there are some updates to the docker images that was uploaded.  Also, updated github action test build files.  The only case that could not be tested is building with the linux docker version on windows.  Since the windows docker version works on windows, it should be enough.  Also, I tried to find a workaround to needing to do chmod 777.  None of the workaround options were very easy to do.  It should be ready to go with the current changes.  Please test and let me know if you find other issues.

**Pull request closed without merging**
