### PR TITLE
Add root GNU Makefile

### PR DESCRIPTION
**Pull request by johnoel**
The Make_SS_330_new.sh did not work for me.  So, I create a build file for GNU Makefile developers.

Usage
```
~/stock-synthesis$ make
```

This will build both safe and optimized programs of stock synthesis.

### CODE REVIEW

**Comment by Rick-Methot-NOAA** [comment]
Elizabeth - please review and merge if OK

**Comment by e-gugliotti-NOAA** [comment]
@johnoel this all looks good to me. I was able to compile your updates to stock synthesis locally and run the test models since the github action was not triggered on this pull request. However, if you could share with me why the Make_SS_330_new.sh wasn't working before you created GNU Makefile and share a bit more about what the GNU Makefile does, that would be very helpful. Thank you!

**Review by e-gugliotti-NOAA — APPROVED** [review]

**Comment by iantaylor-NOAA** [comment]
I just successfully build the executable using the new `GNUmakefile` via `$ make` on a Mac, but I had to change a couple things:
* first comment out the first line `ADMB_HOME=~/admb-main/` since my ADMB was installed in a different place. 
* I also had to add a "/" at the end of my existing `ADMB_HOME` variable since that was expected by the file.

I don't really understand the trade-offs of make file vs. shell script, but it seems like it would be fine to have both options available within the SS3 repo if they serve different needs.

**Comment by johnoel** [comment]
The script is fine.  It just took some time to understand how to use it.

Anyhow, I just prefer a Makefile over a script.  It's easier for me.

**Comment by iantaylor-NOAA** [comment]
Documentation of the status-quo compiling tools isn't great, but there's some info here: https://github.com/nmfs-stock-synthesis/stock-synthesis/blob/main/CONTRIBUTING.md#how-to-build-stock-synthesis-from-source. I like the idea of merging this request to add the make file (perhaps after removing the first line about ADMB_HOME) and adding a note about it in that CONTRIBUTING.md file.
Even if it just makes it easier to @johnoel to test things, that's still useful.

**Review by e-gugliotti-NOAA — COMMENTED** [review]
I agree with @iantaylor-NOAA, potentially commenting out the first line and adding a commented out line that describes what is needed to be done to use this here and I will add it to the Contributing.md. A line saying "# to use the GNUmakefile, download and compile admb and add the file name of where admb is stored here"

**Comment by e-gugliotti-NOAA** [comment]
@johnoel and @iantaylor-NOAA Is the GNUmakefile just for compiling on linux/macs or can it be used for windows too? I'm on a mac right now until my replacement laptop comes in so I was testing it locally with that.

**Comment by Rick-Methot-NOAA** [comment]
on my local windows, I use this make file.
[Make_SS_safe.zip](https://github.com/nmfs-stock-synthesis/stock-synthesis/files/11179874/Make_SS_safe.zip)

**Comment by iantaylor-NOAA** [comment]
I think if a Windows computer had all the right things set up it should be able to use the same make file, but the batch file Rick noted (which is in the repository at https://github.com/nmfs-stock-synthesis/stock-synthesis/blob/main/Compile/Make_SS_safe.bat) is working fine for the GitHub actions that compile for Windows, so I think the easiest path would be just sticking with what is currently working.

**Comment by e-gugliotti-NOAA** [comment]
Yes, I agree on the .bat file. The .sh file was even working for me on my mac. I just was curious so that if needed, I could provide instructions in the Contributing.md for the GNUmakefile under both the windows and linux/mac sections, or just the linux/mac section.

**Review by e-gugliotti-NOAA — CHANGES_REQUESTED** [review]
Per the discussion, @johnoel could you comment out the first line and add a commented out line that describes what is needed to be done to use the GNU makefile (ex. 
# replace file path for `ADMB_HOME=~/admb-main/` with the file path to admb on your machine. Then you can use `~/stock-synthesis$ make` to build stock synthesis)?

**Review by e-gugliotti-NOAA — APPROVED** [review]
Thanks for making these changes @johnoel!

**Pull request merged**
