### PR TITLE
update readme with file name changes for doc

### PR DESCRIPTION
**Pull request by e-gugliotti-NOAA**
## Concisely describe what has been changed/addressed in the pull request.

Fix links to user manual tutorials given file name changes to ss3 instead of ss.

* Resolves issue #527

### Where are the relevant files?

- [x] No test files are required for this pull request. -->

### What tests/review still need to be done?

None. 
## Is there an input change for users to Stock Synthesis? 

- [x] No, there was no input change. -->

### CODE REVIEW

**Comment by trevorhutton** [comment]
Thank you for "responding" - however this problem still exists.

**Comment by iantaylor-NOAA** [comment]
Hi @trevorhutton, the old links don't work, but the landing page https://nmfs-stock-synthesis.github.io/doc/ has been updated to point to the new links which do work:
https://nmfs-stock-synthesis.github.io/doc/Getting_Started_SS3.html
https://nmfs-stock-synthesis.github.io/doc/ss3_model_tips.html

The source of the change was a cleanup throughout the SS3 repositories of using "SS3" consistently instead of "SS".

**Comment by iantaylor-NOAA** [comment]
Correction: it was the README that got updated, not the main github.io/doc page.
It may require refreshing https://github.com/nmfs-stock-synthesis/stock-synthesis/ to get the updated links.

**Comment by e-gugliotti-NOAA** [comment]
@trevorhutton Did refreshing the page update the links for you?

**Comment by trevorhutton** [comment]
Dear Elizabeth

No, I still get:

404
File not found
The site configured at this address does not contain the requested file.
If this is your site, make sure that the filename case matches the URL as well as any file permissions.
For root URLs (like http://example.com/) you must provide an index.html file.
Read the full documentation<https://help.github.com/pages/> for more information about using GitHub Pages.
Best

Trev.

**Comment by e-gugliotti-NOAA** [comment]
Can you provide me the link to the page you see these links on?

**Comment by trevorhutton** [comment]
Yes

Home - Stock Synthesis - Virtual Lab (noaa.gov)<https://vlab.noaa.gov/web/stock-synthesis>

Go to 1) and PUSH link to Getting Started.

Best

Trev.

**Comment by e-gugliotti-NOAA** [comment]
Ohhhhhh okay, I think we were just confused on which site you were seeing the bug on. I have now updated those links on vlab so they should work now.

**Comment by trevorhutton** [comment]
Dear Elizabeth

Works perfectly.

In Cairns (Aus) on a business trip), as normally based in Brisbane. Timing is great as now using SS now.

Say hi to Andre for me if you see him,

Best

Trev.

**Pull request merged**
