### PR TITLE
issue #238: update change log for 3.30.19

### PR DESCRIPTION
**Pull request by k-doering-NOAA**
## What issue(s) does this PR address? Describe and add issue numbers, if applicable.
Update the change log ahead of 3.30.19 release.  #238 
- [x] Link issue on pull request

## What tests have been done? Upload any model input files created for testing in a zip file, if possible.
N/A. To compile this change log, I looked through issues with the "Resolved" label and/or the 3.30.19 milestone link

## What tests/review still need to be done? Who can do it, and by when is it needed (ideally)?
@Rick-Methot-NOAA to check if anything is missing or needs to be changed, then merging in if it seems acceptable. This should be done by the time of the 3.30.19 release.

## Check which is true. This PR requires:

- [ ] Changes in r4ss
- [ ] Changes to SS3 manual
- [ ] Changes to SSI (the SS3 GUI)

### CODE REVIEW

**Comment by Rick-Methot-NOAA** [comment]
I still am waiting for Andre to do testing on the fleet-specific bioecon optimization.  I am thinking about pulling it into the main branch after adding a warning to indicate that this feature is in beta mode.

**Comment by k-doering-NOAA** [comment]
@Rick-Methot-NOAA , do you want to merge this into main? Just a reminder it is here.

**Comment by Rick-Methot-NOAA** [comment]
Looks like no entries yet for the change_log for 30.19, so let's check in on this Monday before I start addint to the spreadsheet.
Can you add to the PR template:  "Create entry for the change log".

**Comment by Rick-Methot-NOAA** [comment]
OK.  Existence of this issue was not obvious to me.  How does this new issue relate to the change log entry in issue #238?

**Pull request merged**
