### PR TITLE
option for age 0 selectivity below first spline knot (in new branch) #86

### PR DESCRIPTION
**Pull request by iantaylor-NOAA**
New pull request related to #86. I had some issues with linebreaks creating the appearance of all lines changed in the SS_selex.tpl file, so I transferred the changes to a new `spline_issue_86` branch and confirmed that it compiles and operates the same as the messed up `spline_issue_82789` branch (named after original issue number in VLab).

### CODE REVIEW

**Comment by k-doering-NOAA** [comment]
Thanks @iantaylor-NOAA for taking the time to do this! The failing tests for run-no-est can be ignored, as they are failing because they assume the data.ss_new file should be data_echo.ss_new instead.  Since run-with-est is working, we know there is no change in the models results anyway.

I can do some one-off testing of this feature to make sure it is working as intended.

**Comment by k-doering-NOAA** [comment]
@iantaylor-NOAA could you provide more details on where the new 10, 11, and 12 codes are used for specifying age 0 selectivity below the first spline? I looked in the control file of a skate example (provided in #86 ), but couldn't find it.

**Comment by iantaylor-NOAA** [comment]
@k-doering-NOAA, sorry for the slow follow-up on this. It's the codes described in this section of the User Manual:
https://nmfs-stock-synthesis.github.io/doc/SS330_User_Manual.html#:~:text=For%20a%203,as%20explained%20below
screenshot below
image
[where the "explained below" is:]
image

The inputs (fixed initial values of 10) appear on lines 257 and 279 of the big skate control file.

Would it make sense for me to create a branch of the `doc` repo to modify the text to document this change?

**Comment by k-doering-NOAA** [comment]
I understand now, thanks, Ian! It would be great if you could add documentation for this to the manual (I can edit if you want to submit it as a PR in the doc repo).

I still ran into some issues when I tried to use options 11 and 12 (I naively changed the 10 to a 11 or 12, which caused an error). I'm not sure if I didn't specify the input correctly (perhaps I needed to change some of the other parameter lines?) or if there is something else going on.

**Comment by k-doering-NOAA** [comment]
Also, I looked through the code and nothing jumped out at me as an obvious issue. I also appreciate that you added comments to the code, great idea!

I think this can be merged if 11 and 12 options are working as expected.

**Comment by iantaylor-NOAA** [comment]
@k-doering-NOAA, thanks for checking the other options. 
Codes 11 and 12 are indeed not working properly but it appears to be unrelated to recent changes and instead a problem with the underlying autogen associated with original spline input codes 1 and 2. I've made some progress and think I can probably get it sorted out tomorrow. I add the fixes to this pull request.

**Comment by k-doering-NOAA** [comment]
Sounds good, thanks Ian! I think if you don't have time to sort it out, error messages could be added and another issue opened for the remaining issue.

**Comment by iantaylor-NOAA** [comment]
I think I got the aerogeneration working correctly again so I think this Pull Request is ready for code review and merging if it looks OK.

There were a few issues:
- the `s` index being used for both season and knot counter so things were assigned to the wrong parameter line
- incorrect parentheses leading to a knot at a negative length value
- new options for 0 selectivity below first knot weren't robust to having first knot at first size bin or age 0

These should all now be sorted out in the `spline_issue_86` branch, but merging this can wait until the more important ongoing changes are sorted out and @Rick-Methot-NOAA can look over the changes made in this branch.

**Comment by k-doering-NOAA** [comment]
I tested and 11 and 12 options and got this helpful msg:
```
 no age data for fleet 6: can't autogenerate cubic spline knots 
```
I then used option 10 for this fleet and tried 11 and 12 options for a different fleet and they ran;  same with options 1 and 2. I didn't check the outputs yet to see if they were reasonable, but can do that tomorrow.

**Comment by iantaylor-NOAA** [comment]
Thanks @k-doering-NOAA. 
My quick check of outputs running with `-stopph 0` showed reasonable-looking dome-shaped autogenerated length- and age-based splines for the 3 knot case. I didn't look at larger numbers of knots.

**Comment by k-doering-NOAA** [comment]
I saw the same, but also for 3 knots. If @Rick-Methot-NOAA thinks this is sufficient testing, I'm ok to merge it in; let me know if you would like more extensive testing

**Comment by Rick-Methot-NOAA** [comment]
I'm satisfied.  Thanks for the testing.  I still am bracketing commits from .18 to present to find when some subtle change is affecting gradients with simple_lorenzen

**Comment by k-doering-NOAA** [comment]
Changed WCGBTS len selectivity to option 12 and tried running with 3 and 5 knots.
3 knots:
image
5 knots: 
image

I think this is working as expected and feel we have covered enough of the options now.

**Comment by k-doering-NOAA** [comment]
@Rick-Methot-NOAA, I'll leave this one for you to merge in as well, since you are investigating the lorenzen issue.

**Pull request merged**
