### PR TITLE
320 standardize exit message

### PR DESCRIPTION
**Pull request by nschindler-noaa**
## Concisely (20 words or less) describe the issue
This expands the write_message utility by allowing different levels of messages (Notes and Warnings). It is internal to the code.

## Please Link issue(s)

resolves #[add issue number number], resolves #[optional second issue number if more than 1 issue addressed.]

## Has any new code been documented?

If not, please add documentation before submitting the Pull Request.
- [x ] I have documented any new code added (or no new code was added)

## is there an input change for users to Stock Synthesis? 

- [ ] Yes, there was an input change

If so, please provide an example of the new inputs needed.

```
[New example stock synthesis input goes here]

```

## Check which is true. This PR requires:

- [x] no further changes to r4ss
- [ ] no further changes to the manual
- [x] no further changes to SSI (the SS3 GUI)
- [x] no further changes to the stock synthesis change log (new features, bug reports)

## Describe any changes in r4ss/SS3 manual/SSI that are needed (if not checked):

Add a paragraph to the Manual to describe to users the categories of warnings & notes

## If changes are needed in the change log, please fill in the table here:

| Action                | Topics                                     | Type  |
| --------------------- | ----------------------------------------- | --------------------------------------- |
| revise | documentation, warnings | output |

### CODE REVIEW

**Review by Rick-Methot-NOAA — COMMENTED** [review]
Neal, this is a helpful augmentation of SS3.
It appears that the number of warnings is changed, which is benign but we will need to update the expected number of warnings.
Please work with @chantelwetzel-noaa to add a paragraph to the Manual to describe to users the categories of warnings & notes.

**Comment by Rick-Methot-NOAA** [comment]
I am surprised that this run is failing.  The differences I see in results file are all small.  @k-doering-NOAA  can you take a quick look?

**Comment by kellijohnson-NOAA** [comment]
@Rick-Methot-NOAA the first job is failing b/c the number of "warnings" has changed.

**Comment by kellijohnson-NOAA** [comment]
For the estimation run it looks like many differences in very small numbers referring to Sum_recdevs_like and maxgrad, where below I pasted the differences sorted by the calculated percent change for and subset for non-zero percent change. I am not super familiar with this file so I am not sure what is common here.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/kelli/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/kelli/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



quantity | value | ref_value | diff | perc_change | ratio | mod_name
-- | -- | -- | -- | -- | -- | --
Sum_recdevs_like | 0.0000 | 0.0000 | 0.0000 | -442.6720 | -3.4267 | tagging_mirrored_sel
Sum_recdevs_like | 0.0000 | 0.0000 | 0.0000 | -440.1380 | -3.4014 | growth_morphs
Sum_recdevs_like | 0.0000 | 0.0000 | 0.0000 | -275.0001 | -1.7500 | Simple
Sum_recdevs_like | 0.0000 | 0.0000 | 0.0000 | -223.0773 | -1.2308 | two_morph_seas_areas
Sum_recdevs_like | 0.0000 | 0.0000 | 0.0000 | -141.9350 | -0.4194 | Empirical_Wtatage_Age_Selex
Sum_recdevs_like | 0.0000 | 0.0000 | 0.0000 | -137.4999 | -0.3750 | Simple_with_Discard
Sum_recdevs_like | 0.0000 | 0.0000 | 0.0000 | -122.5352 | -0.2254 | Simple_NoCPUE
InitEQ_regime_like | 0.0000 | 0.0000 | 0.0000 | -100.0000 | 0.0000 | Sablefish2015
InitEQ_regime_like | 0.0000 | 0.0000 | 0.0000 | -100.0000 | 0.0000 | two_morph_seas_areas
maxgrad | 0.0000 | 0.0008 | -0.0007 | -94.3487 | 0.0565 | vermillion_snapper_F4
maxgrad | 0.0000 | 0.0000 | 0.0000 | -83.5073 | 0.1649 | Simple_NoCPUE
maxgrad | 0.0000 | 0.0000 | 0.0000 | -82.3051 | 0.1769 | Simple
maxgrad | 0.0000 | 0.0001 | -0.0001 | -74.6744 | 0.2533 | growth_morphs
Sum_recdevs_like | 0.0000 | 0.0000 | 0.0000 | -44.4446 | 0.5556 | Sablefish2015
Sum_recdevs_like | 0.0000 | 0.0000 | 0.0000 | -44.4443 | 0.5556 | three_area_nomove
maxgrad | 0.0001 | 0.0001 | 0.0000 | -28.8089 | 0.7119 | Empirical_Wtatage_Age_Selex
maxgrad | 0.0000 | 0.0000 | 0.0000 | -3.9230 | 0.9608 | Simple_with_Discard
maxgrad | 0.0001 | 0.0001 | 0.0000 | -0.0414 | 0.9996 | two_morph_seas_areas
Parm_softbounds_like | 0.0014 | 0.0014 | 0.0000 | -0.0084 | 0.9999 | growth_morphs
Recruitment_like | 1.5023 | 1.5023 | 0.0000 | -0.0007 | 1.0000 | growth_morphs
Bratio_2001 | 0.3064 | 0.3064 | 0.0000 | -0.0003 | 1.0000 | growth_morphs
ForeCatch_2004_val | 3449.6400 | 3449.6500 | -0.0100 | -0.0003 | 1.0000 | growth_morphs
Recruitment_like | -4.3298 | -4.3298 | 0.0000 | -0.0002 | 1.0000 | Simple_Lorenzen_tv_trend
Parm_softbounds_like | 0.0075 | 0.0075 | 0.0000 | -0.0001 | 1.0000 | vermillion_snapper_F4



</body>

</html>

**Comment by Rick-Methot-NOAA** [comment]
Thanks for looking Kelli.  That is the same file I have been looking at.  Refinement of the fail criteria has been difficult given the large range of absolute values for these quantities.

**Review by Rick-Methot-NOAA — APPROVED** [review]
ready to merge

**Comment by nschindler-noaa** [comment]
Chantel, here are the categories of Notes/Messages:
Notes:
Information : Some information that could be useful
Suggestion : This is a possible better way
Warnings:
Performance : A change that can help performance
(no category) : This might be a problem, but execution continues anyway
Adjustment : An adjustment has been made, and execution continues
Fatal Error! : There is a major problem, program will exit

**Comment by k-doering-NOAA** [comment]
thanks @kellijohnson-NOAA and @Rick-Methot-NOAA for taking a look. I think the run-with-est job was failing because the warning file syntax has changed and it couldn't pull out the number of warnings from warnings.sso correctly anymore. Here is where the warning is coming from: https://github.com/nmfs-stock-synthesis/test-models/blob/07f20126d2bc41747d811c3b8191d449292d9d6b/.github/r_scripts/compare.R#L297

here is where you can see the job failing: https://github.com/nmfs-stock-synthesis/stock-synthesis/runs/7779234003?check_suite_focus=true#step:10:80

As for the build-warnings job, I think Kelli is right about the cause. To troubleshoot this, I would compare the warning file produced from this run versus one from an earlier run on main that was passing and use a text compare tool to see which warnings are new. If they are comfirmed as "ok" warnings, then we can change the number of warnings expected in this job (currently it expects 83 warnings): https://github.com/nmfs-stock-synthesis/workflows/blob/a62a6c65cd146ceebd3cac4b612cf3d86c0d58d9/.github/workflows/build-ss3-warnings.yml#L64

**Comment by Rick-Methot-NOAA** [comment]
Let's wait to update the warning count until after we convert to ADMB 13.0.  I suspect it will change.

**Comment by k-doering-NOAA** [comment]
Yes, I think it will, probably the number will decrease, so it would be good to recalibrate the number at that time.

**Pull request merged**
