### PR TITLE
325 make platoon variance ratio a parameter

### LINKED ISSUE #325: make platoon variance ratio a parameter
While working on a project fitting SS3 with 5 platoons to data generated by an IBM, there was evidence that the constant, sd_ratio, that controls the variance of length-at-age within each platoon relative to the variance among the means of the platoons, is not trivial and affects the logL and growth parameter estimates.  Hence it should be estimable.
Currently, sd_ratio is read in ss_readcontrol, and immediately used to calculate sd_between and sd_within.
Then in SS_ALK, sd_between and sd_within are used to calculate the mean and sd of length-at-age for each platoon.

Proposal:
a.  read sd_ratio as a MGparm, rather than a constant.  Seems logical to insert this parameter after the cohort_growth_dev parameter and before the movement parameters.
b.  move calculation of sd_within and sd_between to SS_ALK where they will be estimated dynamically as the parameter, sd_ratio, is estimated.
c.  come up with a better name for the parameter that has the function of sd_ratio.
d.  do this project as the next group coding session to expose group to the indexing of MGparms

### PR DESCRIPTION
**Pull request by nschindler-noaa**
## Concisely (20 words or less) describe the issue
Changes sd_ratio from value to parameter. Adds a parameter to the MG params.

## Please Link issue(s)

resolves #325

## What tests have been done? Upload any model input files created for testing in a zip file, if possible.
[test_platoon_varparm.zip](https://github.com/nmfs-stock-synthesis/stock-synthesis/files/10829744/test_platoon_varparm.zip)

## What tests/review still need to be done? Who can do it, and by when is it needed (ideally)?
none needed.

## Has any new code been documented?
Yes.
Modifications made to readcontrol such that an additional MGparm line is read if sd_ratio is < 0.
In ALK, the key change is:
    if (sd_ratio_rd < 0)   {
      dvar_platoon_ratio = MGparm(sd_ratio_param_ptr);

If not, please add documentation before submitting the Pull Request.
- [x] I have documented any new code added (or no new code was added)

## is there an input change for users to Stock Synthesis? 

- [x] Yes, there was an input change

If so, please provide an example of the new inputs needed.
in the control file,
```
5 #_N_platoons_Within_GrowthPattern 
-1.09227 #_Platoon_within/between_stdev_ratio (no read if N_platoons=1)
#_Cond sd_ratio_rd < 0: platoon_sd_ratio parameter required after movement params.
 0.031 0.237 0.464 0.237 0.031 #vector_platoon_dist_(-1_in_first_val_gives_normal_approx)
Then
# Movement
# Platoon StDev Ratio 
 0.1 10 1.09227 0.7 99 0 3 0 0 0 0 0 0 0 # Platoon_SD_Ratio
# Age Error from parameters
```

## Check which is true. This PR requires:

- [ ] no further changes to r4ss
- [ ] no further changes to the manual
- [ ] no further changes to SSI (the SS3 GUI)
- [ ] no further changes to the stock synthesis change log (new features, bug reports)

## Describe any changes in r4ss/SS3 manual/SSI that are needed (if not checked):
requires review

## If changes are needed in the change log, please fill in the table here:

| Action                | Topics                                     | Type  |
| --------------------- | ----------------------------------------- | --------------------------------------- |
| [fix, new, or revise] | [e.g., biology. Use issue label options.] | [input, output, and/or calc, or ALL] |

### CODE REVIEW

**Comment by nschindler-noaa** [comment]
This needs SSI changes and document changes. Most probably r4ss changes also. the control file has one line deleted (the value) and one line added (the parameter after movement parameters).

**Review by Rick-Methot-NOAA — CHANGES_REQUESTED** [review]
Hi Neal.  Good start on this.
In ALK, do not use value() as it will break the derivative chain and disable estimation of the parameter.
Also, let's consult with Ian regarding whether to just implement this change, or to make it conditional such that existing models that use constant sdratio can still read inputs and work.
@iantaylor-NOAA

**Comment by nschindler-noaa** [comment]
okay, @Rick-Methot-NOAA or @iantaylor-NOAA , what do I use to get the number from the vector? I can't seem to find out anything from the online documentation for ADMB

**Comment by Rick-Methot-NOAA** [comment]
I'll give it a try on one of my examples

**Comment by Rick-Methot-NOAA** [comment]
I think we are close, but gradients are not right.  I tried the derivative checker in ADMB and the numerical derivative was quite different than the analytical.  I will look into this more closely soon.

**Comment by Rick-Methot-NOAA** [comment]
Neal - I think it is working with the changes I added.  Here is my test example. 
[test_platoon_varparm.zip](https://github.com/nmfs-stock-synthesis/stock-synthesis/files/10746550/test_platoon_varparm.zip)

**Comment by nschindler-noaa** [comment]
Looks good to me.

**Comment by Rick-Methot-NOAA** [comment]
I see that the test model check fails when running the "growth_morphs" example.  That is because we did not build in backward compatibility.  I still agree with Ian that we don't need backward compatibility, so let's update the test example so it will use the new version of growth morphs.  @e-gugliotti-NOAA

**Comment by e-gugliotti-NOAA** [comment]
Will update the growth platoons test model after I merge the v3.30.21 test model updates.

**Comment by Rick-Methot-NOAA** [comment]
Hmmm.  We have a sequencing issue because this feature will not be released until 3.30.22.  Perhaps temporarily remove this example from the set until we modify it to use the new approach???

**Comment by Rick-Methot-NOAA** [comment]
@nschindler-noaa 
I have changed my mind regarding backward compatibility.    It seems that it will be fairly straightforward to add for this feature.
Logic goes as:
if Nplatoons > 1 then read sdratio_rd
if sdratio_rd > 0 then copy it to sdratio and use it
else
invoke reading of parameter for sdratio per current code.

**Comment by iantaylor-NOAA** [comment]
Thanks Rick,
This will make the r4ss solution (which we didn't yet embark on) for reading the control file easier more straightforward as well. Sorry I didn't think of something like this earlier.

**Comment by nschindler-noaa** [comment]
I am making some changes for backward compatibility. The control files will need to at least include the sd-ratio value. If there are more that one platoon AND the sd-ratio is negative, then it will look for a parameter.

**Comment by Rick-Methot-NOAA** [comment]
It seems feasible to make reading of sd_ratio_rd conditional on N_platoons>1.

**Comment by nschindler-noaa** [comment]
Yes, like current main. Just adding logic for when sd_ratio_rd is negative.

**Comment by Rick-Methot-NOAA** [comment]
Thanks Neal.  All checks passed so the backward compatibility is working.  I'll take a closer look before approving.

**Review by Rick-Methot-NOAA — COMMENTED** [review]
I think the conditional logic is a bit more complicated than it needs to be.
In readcontrol, if line 96 changed to sd_ratio_rd = 0
then conditional at line 121 is unnecessary because N_platoon > 1 anytime sd_ratio_rd > 0

It's too bad that we cannot simplify ALK such that it does not need two versions of the code.
Better if we could do:
      if (sd_ratio_rd < 0) plat_sd_ratio = MGparm(sd_ratio_param_ptr);
      else
      plat_sd_ratio = sd_ratio_rd;
      
      but ADMB does not allow setting a dvariable equal to a constant.

**Comment by kellijohnson-NOAA** [comment]
Can't you just trick ADMB and make it a parameter that is not estimated, i.e., with a negative phase?

**Comment by Rick-Methot-NOAA** [comment]
True, and that is how all parameters work when they get assigned an initial value from what is read from the control file.  But the logic of doing that in this case and allowing the backward compatible approach that does not have a parameter seemed complex also.   I would like to avoid extra conditional statements inside of ALK.
I suppose the code could:
a.  create a global  dvariable that is the quantity that will be used in ALK
b.  in the backward compatible case, assign that dvariable to the constant that is read (I think that would happen in PRELIM calcs)
c.  in the new parameter approach, do that assignment dynamicly, probably in the MGSETUP.

**Comment by nschindler-noaa** [comment]
When I create a 'dvariable' before reading the sd ratio, I cannot compile. Even if I change 'number' to 'double'.

**Comment by Rick-Methot-NOAA** [comment]
Current code works and achieves backward compatibility, so no rush.  I can take a look later this week.

**Comment by nschindler-noaa** [comment]
Would it be reasonable to assume that if sd_ratio_rd is negative, then there are more than 1 platoons?

**Comment by Rick-Methot-NOAA** [comment]
sd_ratio_rd is only read if n_platoons is > 1.
suggest assigning it value of 0 if not read

**Comment by Rick-Methot-NOAA** [comment]
The code that I think can be streamlined is in ALK.
This IF statement at line 95 could be eliminated if the value in sd_betw_plat_parm could be set before the "g" loop
			  if (sd_ratio_rd < 0)
			  {
                Sd_Size_between(ALK_idx, g) = Sd_Size_within(ALK_idx, g) * sd_betw_plat_parm;
                Sd_Size_within(ALK_idx, g) *= sd_with_plat_parm;
			  }
			  else
			  {
                Sd_Size_between(ALK_idx, g) = Sd_Size_within(ALK_idx, g) * sd_between_platoon;
                Sd_Size_within(ALK_idx, g) *= sd_within_platoon;
			  }

**Comment by nschindler-noaa** [comment]
sd_ratio_rd is already set to 1. if N_platoons == 1. if sd_ratio_rd is < 0, then it has read a value, therefore there are more than 1 platoons.

**Comment by nschindler-noaa** [comment]
I think the following code will work in SS_ALK:
    if (sd_ratio_rd < 0) // calculate the between and within stdev ratio
    {
      platoon_sd_ratio = MGparm(sd_ratio_param_ptr).xval();
      sd_between_platoon = sqrt(1. / (1. + platoon_sd_ratio * platoon_sd_ratio));
      sd_within_platoon = platoon_sd_ratio * sd_between_platoon;
    }
These values are already computed once when the positive value for sd_ratio_rd is read. Then, the code following is much simpler (and I hope I've got this right this time):
            if (N_platoon > 1)
            {
              Sd_Size_between(ALK_idx, g) = Sd_Size_within(ALK_idx, g) * sd_between_platoon;
              Sd_Size_within(ALK_idx, g) *= sd_within_platoon;
            }

**Comment by Rick-Methot-NOAA** [comment]
I think there needs to be one more change because the final calculation needs to use dvariable, not a constant number.
      instead of:
      platoon_sd_ratio = MGparm(sd_ratio_param_ptr).xval();
 
something like:
     if(sd_ratio_rd>0)
       {dvar_plat_ratio = platoon_sd_ratio;}
  else
      {dvar_plat_ratio  = MGparm(sd_ratio_param_ptr);}

  then create sd_within_platoon and sd_between using dvar_plat_ratio

**Comment by nschindler-noaa** [comment]
Okay.

**Comment by Rick-Methot-NOAA** [comment]
works great and produces a reasonable parameter value with reasonable variance in my test.  ALK code now much more concise.
One addition will be to copy the dvar quantities, which are local to ALK,  to the constant quantities so they can be reported in write_report at line 3804-3806.

minor tweak:  revise write_new text with sdratio_rd so it will reference link to parameter reading

**Comment by nschindler-noaa** [comment]
I'll need to rename the dvar quantities and add a couple lines. 
For the minor tweak, I thought that's what it was doing. sd_ratio_rd is not changed, so the new file would be the same ... oh, use the negative value of the parameter for sd_ratio_rd?

**Comment by Rick-Methot-NOAA** [comment]
No need to rename.  Just set platoon_sd_ratio = value(dvar_platoon_ratio) in ALK.
ditto for the between and within quantities

**Comment by nschindler-noaa** [comment]
Right.

**Review by Rick-Methot-NOAA — APPROVED** [review]
Thanks Neal.

**Comment by Rick-Methot-NOAA** [comment]
@chantelwetzel-noaa   @iantaylor-NOAA 
Can you revise the manual to include description of this new feature?
Something like:
If user selects >1 platoon and sets the value of sd_ratio to a negative number, then SS3 will read one additional MGparm line:
#  Movement
#  Platoon StDev Ratio 
 0.1 10 1.09227 0.7 99 0 3 0 0 0 0 0 0 0 # Platoon_SD_Ratio
#  Age Error from parameters
Our experience to date is that this parameter is estimable, especially if there is CAAL data included in the model.   The value of sd_ratio controls the degree to which there is fidelity in the growth trajectories of large length-at-age vs small length-at-age fish.  Our experience is that Linf may be underestimated and degree of dome-selectivity mis-estimated if the platoon approach is not used and the population has high fidelity in growth trajectories.   Parameter values in the range of 0.5 to 1.5 are expected.

**Pull request merged**
