### PR TITLE
implement changes and warnings for recr surveys

### PR DESCRIPTION
**Pull request by Rick-Methot-NOAA**
see info with the issue

* Resolves issue #466

## What tests have been done? 
temporary edits to simple example were used to test display of the new warnings
[recr_svy_test.zip](https://github.com/nmfs-stock-synthesis/stock-synthesis/files/12017818/recr_svy_test.zip)

## Is there an input change for users to Stock Synthesis? 

 [x] No, there was no input change.

### CODE REVIEW

**Comment by e-gugliotti-NOAA** [comment]
I ran the growth_timevary test model which has a survey where the unit is 32 and the endyear of that survey is 2009, but the last main recdev year is 2008. I get the following:
`Note 2 Suggestion: Recruitment survey: 4 has data in: 2009, which is after last main recdev: 2008. Suggest extend recdev_end, or change fore_devs phase: 6`
which looks like it's doing what it's supposed to given the code you added.

**Comment by Rick-Methot-NOAA** [comment]
The example you tried had a forecast phase = 6, which is good and so doesn't need change.  I will add a condition such that that warning will only appear if forecast phase is <=0.

**Comment by e-gugliotti-NOAA** [comment]
I ran the test model that you attached and got the note in the warning.sso. I also ran the growth_timevary model which has a survey where the unit is 32 and the last year of that survey is 2009 but the last year of main recdev is 2009. I get the following note:
`Note 2 Suggestion: Recruitment survey: 4 has data in: 2009, which is after last main recdev: 2008. Suggest extend recdev_end, or change fore_devs phase: 6`
so it seems things are working as they should.

**Review by e-gugliotti-NOAA — APPROVED** [review]

**Comment by Rick-Methot-NOAA** [comment]
Thanks.  Please edit the manual per the text I put in the issue #466

**Review by e-gugliotti-NOAA — APPROVED** [review]

**Pull request merged**
