### PR TITLE
Andre bioecon

### PR DESCRIPTION
**Pull request by Rick-Methot-NOAA**
ready for github actions

### CODE REVIEW

**Comment by Rick-Methot-NOAA** [comment]
The vermillion snapper run failed with a difference reported in the forecast.  That run uses some of the byzantine discard options, so is exactly the test I needed to polish up this code.

**Comment by k-doering-NOAA** [comment]
@Rick-Methot-NOAA , here are the additional warnings:
```
ss.cpp:18361:17: warning: implicitly-declared ‘dvariable& dvariable::operator=(const dvariable&)’ is deprecated [-Wdeprecated-copy]
18361 |       Vbio1_MSY=smrybio;
      |                 ^~~~~~~
ss.cpp:18362:16: warning: implicitly-declared ‘dvariable& dvariable::operator=(const dvariable&)’ is deprecated [-Wdeprecated-copy]
18362 |       Vbio_MSY=totbio;
      |                ^~~~~~
ss.cpp:17750:28: warning: variable ‘Nloops1’ set but not used [-Wunused-but-set-variable]
17750 |   int jj;  int Nloops; int Nloops1; int Nloops2;
      |                            ^~~~~~~
      |           ^~~~
ss.cpp: In member function ‘void model_parameters::Get_Benchmarks(int)’:
ss.cpp:18291:19: warning: ‘Nloops2’ may be used uninitialized in this function [-Wmaybe-uninitialized]
18291 |         for (j=0;j<=Nloops2;j++)   // loop to find Fmsy
      |                  ~^~~~~~~~~
```

I think the first 2 can be safely ignored, but the last 2 may be worth checking out!

**Comment by k-doering-NOAA** [comment]
@Rick-Methot-NOAA , now just the implicit warnings remain:
```
18272 |       Vbio_MSY=totbio;
      |                ^~~~~~
ss.cpp:18362:17: warning: implicitly-declared ‘dvariable& dvariable::operator=(const dvariable&)’ is deprecated [-Wdeprecated-copy]
18362 |       Vbio1_MSY=smrybio;
      |                 ^~~~~~~
ss.cpp:18363:16: warning: implicitly-declared ‘dvariable& dvariable::operator=(const dvariable&)’ is deprecated [-Wdeprecated-copy]
```

I will modify the warnings job so it will pass with these added.

Also, do you need review from anyone on the team? And what specifically would you want checked if so? I see reviews were requested from @kellijohnson-NOAA  and @chantelwetzel-noaa , but wanted to check in about this.

**Comment by Rick-Methot-NOAA** [comment]
I added them as reviewers mostly for their awareness.

I think all the warnings regarding "implicitly declared" can be accepted

**Comment by k-doering-NOAA** [comment]
Thanks - number of warnings now updated (in https://github.com/nmfs-stock-synthesis/workflows/commit/08f73293ead8eeddafa297ddca756993c4c1e64f) . I think you are all set to merge in, if you feel it is ready!

**Comment by kellijohnson-NOAA** [comment]
@Rick-Methot-NOAA you had originally asked for a review from @chantelwetzel-noaa or I. I know that Chantel is at a Council meeting. But, I am happy to look at something in particular if you still want a review?

**Review by chantelwetzel-noaa — APPROVED** [review]
@Rick-Methot-NOAA Thank you for tagging me as a reviewer to ensure I saw this new model revision.  I have been following your exchanges with Andre which has provided clear instructions on the I/O changes.  The code revisions look consistent with those descriptions. Since it appears that these changes have been tested by yourself and Kathryn on test models, I think these changes are ready for merging.

**Comment by Rick-Methot-NOAA** [comment]
only warning is in the compiler extended warning count on linux.  Need to continue refining that test. Merging into main now.

**Pull request merged**
