### PR TITLE
471 bug gradient issue with forecast recruitment option 3

### PR DESCRIPTION
**Pull request by nschindler-noaa**
## Concisely describe what has been changed/addressed in the pull request.
Added a Warning: Adjustment when forecast recruitment option is 3 or 4 and end_recruits year is not equal to endyr.

* Resolves issue #471

### Where are the relevant files?

[x] Test files are in the issue. 

## Is there an input change for users to Stock Synthesis? 

[x] No, there was no input change.

### CODE REVIEW

**Review by Rick-Methot-NOAA — CHANGES_REQUESTED** [review]
This is not the correct adjustment.  The change needs to be in readcontrol to recdev_end.  Right after this section:
  //  SS_Label_Info_4.6.4 #Setup recruitment deviations and create parm labels for each year
  if (recdev_end > retro_yr)
  {
    warnstream << " recdev_end: " << recdev_end << " > retro_yr: " << retro_yr << " reset ";
    write_message (ADJUST, 0);
    recdev_end = retro_yr;
  }

Add something like:
if(recdev_end < endyr && (Fcast_Loop_Control(3) == 3 || Fcast_Loop_Control(3) == 4)

**Comment by nschindler-noaa** [comment]
Okay. I've redone the adjustment (changing recdev_end now).

**Comment by nschindler-noaa** [comment]
I don't know why the tests are failing. The models run, but the checks don't pass?

**Comment by Rick-Methot-NOAA** [comment]
looks like problem is in variance calculation for vermillion snapper.  I will try it offline so can diagnose the details.

**Comment by Rick-Methot-NOAA** [comment]
The result is different because the vermillion test file does not follow the rules.  I am surprised it worked before.  Several warnings.

Warning 2 : Mean recruitment for forecast is incompatible with pos. phase for forecast rec_devs; set phase to neg. unless using late rec_devs
Warning 3 Adjustment: Fcast recr option is 3 or 4 and recdev_end: 2015 < endyr: 2017 reset 
Warning 5 : This option (mean recruitment) may be deprecated; same as forecast option(5), averaging parameters, type 4.

**Comment by e-gugliotti-NOAA** [comment]
@Rick-Methot-NOAA I changed the year for that test model file in the control and re-ran one of those actions but it still seems to be failing [here](https://github.com/nmfs-stock-synthesis/stock-synthesis/actions/runs/5468867513).

**Comment by Rick-Methot-NOAA** [comment]
The -noest run is expected to fail because the new tpl causes an expected change to estimation of the last two recruitments.
When I run with est locally, I am getting a reasonable result.  Here is the reference and new ss_summary I get when running the original model files with 3.30.21 and 3.30.new
[compare.zip](https://github.com/nmfs-stock-synthesis/stock-synthesis/files/11962274/compare.zip)

**Comment by e-gugliotti-NOAA** [comment]
Okay sounds good, will work through the est action today. I found a place where changes needed to be made in the R code for the no-est action yesterday, so that has also been fixed.

**Comment by e-gugliotti-NOAA** [comment]
@Rick-Methot-NOAA Re-running the action in the PR (those are sometimes finicky though) but the when I ran it manually the run-ss3-with-est action was successful on this branch is also [here](https://github.com/nmfs-stock-synthesis/stock-synthesis/actions/runs/5476760631)

**Review by Rick-Methot-NOAA — APPROVED** [review]

**Comment by e-gugliotti-NOAA** [comment]
@Rick-Methot-NOAA, the build-ss3-warnings action only builds and gets those warnings for a linux machine. I'm not sure if they will appear on a windows or mac machine yet. @nschindler-noaa, did you see [these warnings](https://github.com/nmfs-stock-synthesis/stock-synthesis/actions/runs/5417818839/jobs/9849207461?pr=473#step:6:30) when building on a windows machine? That's the next line of inquiry I can think of.

**Pull request merged**
