### PR TITLE
fix #165 for bounded link; add survey type #41

### LINKED ISSUE #165: Implement bounded env_link for density-dependent parameters
Thanks to @nathanvaughan-NOAA for discovering this. The bounded init link is [not implemented](https://github.com/nmfs-stock-synthesis/stock-synthesis/blob/bd721572cb2ad8d452756145db4794400757788f/SS_timevaryparm.tpl#L347) for linking a parameter to a model-derived quantities. I just tried running a model with this option - simple but with [this selectivity line](https://github.com/nmfs-stock-synthesis/ss-test-models/blob/56a86200529ca9e8537387194e52af8d250ee0a6/models/Simple/control.ss#L240) changed to 

```
19            70        36.653            30          0.01             1          2          -303        0          0          0          0          0          0  #  Size_inflection_SURVEY1(2)
```

and got the error `array bound exceeded -- index too high in prevariable::operator()`

I think it would be helpful to either implement the bounded init link (could code just be copy/pasted from the [env links section](https://github.com/nmfs-stock-synthesis/stock-synthesis/blob/main/SS_timevaryparm.tpl#L202-L214)?) or to provide a more informative error msg on why this option is not available or allowed. We may need want to update the manual, too based on what is implemented.

### PR DESCRIPTION
**Pull request by Rick-Methot-NOAA**
enable use of density-dependence with a bounded link env.
add survey type 36 as survey of a recdev

## Concisely (20 words or less) describe the issue
bounded env link was not implemented for density dependence
## Please Link issue(s)
#165 #41  #390 
resolves #[add issue number number], resolves #[optional second issue number if more than 1 issue addressed.]
#165 #41 
## What tests have been done? Upload any model input files created for testing in a zip file, if possible.
create test using "simple" example.  Temporarily added extra echoinput statements to verify that correct calculations are occurring
## What tests/review still need to be done? Who can do it, and by when is it needed (ideally)?
@nathanvaughan-NOAA submitted original request, so useful for him to review this
## Has any new code been documented?
yes
If not, please add documentation before submitting the Pull Request.
- [X] I have documented any new code added (or no new code was added)

## is there an input change for users to Stock Synthesis? 
density-dependent env link now works.  It was a  broken option before this code update
If so, please provide an example of the new inputs needed.

```
[New example stock synthesis input goes here]

```

## Check which is true. This PR requires:

- [ 
- [X] no further changes to r4ss
- [X] no further changes to the manual
- [ ] no further changes to SSI (the SS3 GUI)
- [ ] no further changes to the stock synthesis change log (new features, bug reports)

## Describe any changes in r4ss/SS3 manual/SSI that are needed (if not checked):
clarify that env link -303 is now OK to use.
add survey type 36
## If changes are needed in the change log, please fill in the table here:
will add changelog label to the issue

### CODE REVIEW

**Comment by Rick-Methot-NOAA** [comment]
@nschindler-noaa  Can you review this pull request?

**Comment by nschindler-noaa** [comment]
Will review tomorrow.

**Comment by Rick-Methot-NOAA** [comment]
@nathanvaughan-NOAA 
Nathan - can you take a quick look at the code changes?

**Comment by Rick-Methot-NOAA** [comment]
@e-gugliotti-NOAA  I asked Nathan to take a look at the code, but he cannot do the review.  I should be able to bypass review but for unknown reason I cannot for this PR.

**Comment by nathanvaughan-NOAA** [comment]
Hey Rick, I’m on leave away from my computer but I can take a look at it tomorrow if that is not too late. Cheers,Nathan Sent from my iPhoneOn Feb 7, 2023, at 9:16 AM, Richard Methot ***@***.***> wrote:﻿
@nathanvaughan-NOAA
Nathan - can you take a quick look at the code changes?

**Review by e-gugliotti-NOAA — APPROVED** [review]
@Rick-Methot-NOAA approved the changes so you can merge.

**Review by nathanvaughan-NOAA — APPROVED** [review]
These changes all look good to me. I will test out the changes with one of our SE species after I get back to the office next week.

**Pull request merged**
