### PR TITLE
create skeleton for MV_Tweedie

### PR DESCRIPTION
**Pull request by Rick-Methot-NOAA**
## What issue(s) does this PR address? Describe and add issue numbers, if applicable.

- [ #266 ] Link issue on pull request

## What tests have been done? Upload any model input files created for testing in a zip file, if possible.
none
## What tests/review still need to be done? Who can do it, and by when is it needed (ideally)?
everything
## Check which is true. This PR requires:

- [x] Changes in r4ss
- [x] Changes to SS3 manual
- [x] Changes to SSI (the SS3 GUI)
- [x] An entry in the stock synthesis change log (new features, bug reports)

### CODE REVIEW

**Comment by k-doering-NOAA** [comment]
Great to see this getting worked on! Perhaps we should leave this as a PR until after the 3.30.19 release?

**Comment by Rick-Methot-NOAA** [comment]
definitely longer term than 3.30.19.

**Comment by Rick-Methot-NOAA** [comment]
Thanks.  The transitional-SPR branch has many more edits, so I think it will be easier to restyle it before merge.

**Comment by k-doering-NOAA** [comment]
> Thanks. The transitional-SPR branch has many more edits, so I think it will be easier to restyle it before merge.

Yes, I took a look and agree that seems the best path forward.

**Comment by k-doering-NOAA** [comment]
The new warnings on this branch (that may need to be dealt with) are:

```
ss.cpp:24438:5: warning: this ‘for’ clause does not guard... [-Wmisleading-indentation]
24438 |     for (i = 1; i <= nobs_mnwt; i++)
      |     ^~~
ss.cpp:24443:7: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘for’
24443 |       if (do_once == 1)
      |       ^~
ss.cpp:24573:68: warning: implicitly-declared ‘dvariable& dvariable::operator=(const dvariable&)’ is deprecated [-Wdeprecated-copy]
24573 |     tweedie_Phi = mfexp(selparm(Comp_Err_Parm_Start+Comp_Err_L2(f)));
      |                           
```

**Comment by Rick-Methot-NOAA** [comment]
I closed this PR due to too many conflicts to deal with.
Before closing, I created a new branch, MV-Tweedie-ver2, based on main and with the relevant new code

**Pull request closed without merging**
